application: wwcp540
version: 1
runtime: go
api_version: go1

skip_files:
- ^tools
- ^(.*/)?.*~
- \.hg
- ^wwcpclient/

admin_console:
  pages:
  - name: AppStats
    url: /_ah/stats/

inbound_services:
- warmup

builtins:
- datastore_admin: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /feeds/.*
  script: _go_app
  login: required

- url: .*
  script: _go_app
  login: optional

